import { Asset, Goal, Liability, Profile, RealEstateProject, Snapshot } from "../types";

// ⚠️ DONNÉES FICTIVES — compte de démonstration. Jamais mélangées aux données réelles :
// le mode démo remplace l'état courant et s'affiche avec un bandeau permanent.

export const demoProfile: Profile = {
  firstName: "Camille (démo)",
  age: 34,
  familyStatus: "En couple",
  children: 1,
  country: "France",
  jobStatus: "Salarié·e en CDI",
  netMonthlyIncome: 3200,
  partnerMonthlyIncome: 2400,
  incomeStability: "stable",
  monthlySavings: 900,
  monthlyExpenses: 3800,
  knowledgeLevel: "intermédiaire",
  objectives: ["Investir dans l'immobilier", "Atteindre l'indépendance financière"],
  riskTolerance: "équilibré",
  horizonYears: 15,
};

const now = new Date().toISOString();

export const demoAssets: Asset[] = [
  {
    id: "demo-rp",
    category: "immobilier",
    subtype: "Résidence principale",
    name: "Maison — Nantes",
    currentValue: 340000,
    ownershipPct: 100,
    updatedAt: now,
    city: "Nantes",
    address: "12 rue de Strasbourg, Nantes",
    lat: 47.2181,
    lng: -1.5528,
    surface: 95,
    purchasePrice: 295000,
    notaryFees: 22000,
    works: 15000,
    linkedLoanId: "demo-loan-rp",
  },
  {
    id: "demo-locatif",
    category: "immobilier",
    subtype: "Appartement locatif",
    name: "T2 locatif — Angers",
    currentValue: 145000,
    ownershipPct: 100,
    updatedAt: now,
    city: "Angers",
    address: "8 rue Plantagenêt, Angers",
    lat: 47.4698,
    lng: -0.5556,
    surface: 42,
    purchasePrice: 128000,
    notaryFees: 10200,
    works: 8000,
    monthlyRent: 620,
    monthlyCharges: 80,
    propertyTax: 780,
    insuranceYearly: 180,
    managementPct: 7,
    vacancyPct: 5,
    taxRegime: "LMNP réel",
    linkedLoanId: "demo-loan-locatif",
  },
  {
    id: "demo-livret",
    category: "liquidites",
    subtype: "Livret A",
    name: "Livret A",
    currentValue: 14500,
    ownershipPct: 100,
    updatedAt: now,
    bank: "Banque Demo",
    ratePct: 2.4,
  },
  {
    id: "demo-cc",
    category: "liquidites",
    subtype: "Compte courant",
    name: "Compte courant joint",
    currentValue: 3200,
    ownershipPct: 100,
    updatedAt: now,
    bank: "Banque Demo",
  },
  {
    id: "demo-pea",
    category: "financier",
    subtype: "PEA",
    name: "PEA — ETF Monde",
    currentValue: 28400,
    ownershipPct: 100,
    updatedAt: now,
    envelope: "PEA",
    invested: 24000,
    monthlyContribution: 300,
    riskLevel: "élevé",
  },
  {
    id: "demo-av",
    category: "financier",
    subtype: "Assurance-vie",
    name: "Assurance-vie — fonds euros + UC",
    currentValue: 19800,
    ownershipPct: 100,
    updatedAt: now,
    envelope: "Assurance-vie",
    invested: 18000,
    monthlyContribution: 150,
    riskLevel: "modéré",
  },
  {
    id: "demo-per",
    category: "financier",
    subtype: "PER",
    name: "PER individuel",
    currentValue: 7600,
    ownershipPct: 100,
    updatedAt: now,
    envelope: "PER",
    invested: 7000,
    monthlyContribution: 100,
    riskLevel: "modéré",
  },
  {
    id: "demo-btc",
    category: "crypto",
    subtype: "Bitcoin",
    name: "Bitcoin",
    currentValue: 6200,
    ownershipPct: 100,
    updatedAt: now,
    platform: "Plateforme Demo",
    quantity: 0.08,
    avgPrice: 52000,
    custody: "plateforme",
    riskLevel: "élevé",
  },
];

export const demoLiabilities: Liability[] = [
  {
    id: "demo-loan-rp",
    type: "Crédit immobilier",
    name: "Prêt résidence principale",
    initialCapital: 265000,
    remainingCapital: 208000,
    monthlyPayment: 1180,
    insuranceMonthly: 62,
    ratePct: 1.6,
    rateType: "fixe",
    endDate: "2043-06-01",
    linkedAssetId: "demo-rp",
    updatedAt: now,
  },
  {
    id: "demo-loan-locatif",
    type: "Crédit immobilier",
    name: "Prêt T2 Angers",
    initialCapital: 135000,
    remainingCapital: 121000,
    monthlyPayment: 585,
    insuranceMonthly: 28,
    ratePct: 3.1,
    rateType: "fixe",
    endDate: "2044-01-01",
    linkedAssetId: "demo-locatif",
    updatedAt: now,
  },
];

export const demoGoals: Goal[] = [
  {
    id: "demo-goal-fi",
    name: "Indépendance financière",
    targetAmount: 1000000,
    currentAmount: 235900,
    monthlyContribution: 900,
    targetDate: "2046-01-01",
    expectedReturnPct: 4,
    createdAt: now,
  },
  {
    id: "demo-goal-apport",
    name: "Apport immeuble de rapport",
    targetAmount: 40000,
    currentAmount: 14500,
    monthlyContribution: 400,
    targetDate: "2029-06-01",
    expectedReturnPct: 2.4,
    createdAt: now,
  },
];

export const demoProjects: RealEstateProject[] = [
  {
    id: "demo-projet-immeuble",
    createdAt: now,
    name: "Immeuble de rapport — Cholet (démo)",
    city: "Cholet",
    postalCode: "49300",
    address: "5 rue Nationale, Cholet",
    lat: 47.0602,
    lng: -0.8791,
    listingUrl: "",
    propertyType: "Immeuble",
    surface: 210,
    residentialLots: 4,
    commercialLots: 1,
    commercialMonthlyRent: 480,
    analysisMode: "approfondie",
    rentalMode: "classique",
    targetNetYieldPct: 7,
    price: 240000,
    agencyFees: 9000,
    notaryFeesPct: 8,
    works: 35000,
    furniture: 8000,
    bankFees: 2000,
    downPayment: 35000,
    ratePct: 3.4,
    durationYears: 20,
    insurancePctYearly: 0.3,
    monthlyRent: 1780,
    monthlyCharges: 210,
    propertyTaxYearly: 2300,
    ownerInsuranceYearly: 600,
    managementPct: 7,
    maintenancePct: 5,
    vacancyPct: 8,
    taxRatePct: 30,
    rentGrowthPct: 1,
    valueGrowthPct: 1,
  },
  {
    id: "demo-projet-t3",
    createdAt: now,
    name: "Petit immeuble 3 lots — Saint-Nazaire (démo)",
    city: "Saint-Nazaire",
    postalCode: "44600",
    address: "22 avenue de la République, Saint-Nazaire",
    lat: 47.2733,
    lng: -2.2137,
    listingUrl: "",
    propertyType: "Immeuble",
    surface: 130,
    residentialLots: 3,
    commercialLots: 0,
    commercialMonthlyRent: 0,
    analysisMode: "express",
    rentalMode: "classique",
    targetNetYieldPct: 7,
    price: 105000,
    agencyFees: 0,
    notaryFeesPct: 8,
    works: 12000,
    furniture: 0,
    bankFees: 1500,
    downPayment: 22000,
    ratePct: 3.5,
    durationYears: 25,
    insurancePctYearly: 0.3,
    monthlyRent: 1350,
    monthlyCharges: 150,
    propertyTaxYearly: 1300,
    ownerInsuranceYearly: 450,
    managementPct: 0,
    maintenancePct: 5,
    vacancyPct: 8,
    taxRatePct: 30,
    rentGrowthPct: 1,
    valueGrowthPct: 1,
  },
];

/** Historique fictif de patrimoine net pour la démo (18 mois) */
export function demoSnapshots(): Snapshot[] {
  const snaps: Snapshot[] = [];
  const today = new Date();
  let net = 196000;
  for (let i = 17; i >= 0; i--) {
    const d = new Date(today.getFullYear(), today.getMonth() - i, 1);
    const wobble = Math.sin(i * 1.7) * 1800;
    net += 2050 + wobble * 0.15;
    snaps.push({
      date: d.toISOString().slice(0, 10),
      netWorth: Math.round(net + wobble),
      gross: Math.round(net + wobble + 335000),
      debts: 335000,
    });
  }
  return snaps;
}
