import { startAccounts } from './lib/account';
import { AccountBoundary } from './components/AccountAccess';
import './account.css';
import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import App from "./App";
import "./index.css";
import "./invest.css";
import "./luxury.css";
import "./opportunities.css";
import "./experience.css";
void startAccounts();
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><BrowserRouter><AccountBoundary><App /></AccountBoundary></BrowserRouter></React.StrictMode>);
